version: '3.5'

services:
  alfred_hls_service:
    build: .
    image: alfred_hls_service:latest
    container_name: alfred_hls_service
    restart: always
    hostname: alfred_hls_service
    networks:
      - alfred
    command: npm run prod
    volumes:
      - video_data:/home/nodejs/app/recordings
    ports:
      - '3982:3978'

volumes:
  video_data:
    external:
      name: video_data

networks:
  alfred:
    name: alfred
    driver: bridge
